/* DNA Analyzer — datos: rasgos explicados en lenguaje humano + poblaciones de referencia para el mapa. */
'use strict';

/* Cada rasgo tiene: bio (que es, en cristiano), interp (que significa PARA TI) y
   opcionalmente consejo (accion practica). Todo en lenguaje llano. */
const TRAITS = [
  { rs:'4988235', name:'Tolerancia a la lactosa', gene:'MCM6 (LCT)', effect:'A', cat:'Nutrición',
    bio:'La lactasa es la enzima que digiere el azúcar de la leche (lactosa). Muchas personas dejan de producirla al crecer; el alelo T (persistencia) la mantiene activa toda la vida.',
    interp:g=>{const a=(g.match(/A/g)||[]).length;
      return a>=1?['✓ Tu cuerpo digiere bien la leche','Portas el alelo de persistencia: mantienes la lactasa activa de por vida, así que la leche no te da problemas.']
                 :['⚠️ Probable intolerancia a la lactosa','No portas el alelo de persistencia. Al tomar lácteos puedes notar hinchazón o molestias.'];
    },
    studies:[['Enattah et al., Nat Genet 2002 (PMID 11788828)','Identificó el alelo que causa la hipolactasia del adulto.'],
             ['PMID 15114531','Confirma la asociación T→persistencia en europeos.'],
             ['PMID 25625576','La actividad de la lactasa forma un gradiente C/C→C/T→T/T.']]},
  { rs:'762551', name:'Metabolismo de la cafeína', gene:'CYP1A2', effect:'A', cat:'Metabolismo',
    bio:'CYP1A2 es la enzima que elimina la cafeína de tu cuerpo. Hay versiones más rápidas y más lentas.',
    interp:g=>{const a=(g.match(/A/g)||[]).length;
      return a===2?['⚡ Eliminas la cafeína muy rápido','A/A: el café apenas te afecta y no te quita el sueño. Puedes tomarlo tarde sin problema.']
                  :a===1?['Normal: la cafeína te afecta de forma media','A/C: ni muy rápido ni muy lento. El café de tarde puede quitarte el sueño, pero moderado.']
                        :['🐢 La cafeína dura más en tu cuerpo','C/C: eres más sensible. Mejor no tomar café por la tarde, te costará dormir.'];}},
  { rs:'12913832', name:'Color de ojos', gene:'HERC2', effect:'G', cat:'Rasgo físico',
    bio:'HERC2 regula cuánta melanina (pigmento) hay en el iris. Menos melanina = ojos más claros.',
    interp:g=>{const a=(g.match(/A/g)||[]).length;
      return a===2?['👁️ Tendencia a ojos marrones','A/A: este gen (el que más pesa) apunta a ojos marrones ~80% de las veces. (El color lo deciden varios genes.)']
                  :a===1?['👁️ Color de ojos mixto','A/G: entre marrón y claro.']:['👁️ Tendencia a ojos azules','G/G: ~99% ojos azules/verdes.'];},
    studies:[['Eiberg et al., Hum Genet 2008 (PMID 18172690)','Asoció G/G con ojos azules en un haplotipo del cromosoma 15.'],
             ['PMID 18252222','OCA2/HERC2 determinan el color azul-marrón.'],
             ['PMID 18650849','Correlaciones con variación de piel, ojos y pelo.']]},
  { rs:'4680', name:'COMT (Val158Met)', gene:'COMT', effect:'A', cat:'Neurobiología',
    bio:'COMT es la enzima que descompone la dopamina, una sustancia del cerebro ligada al ánimo, la motivación y el placer.',
    interp:g=>{const a=(g.match(/A/g)||[]).length;
      return a===2?['🧠 Versión Met/Met','Tu cerebro mantiene la dopamina más tiempo (degradación lenta).']
                  :a===1?['🧠 Versión intermedia (Val/Met)','Equilibrio de dopamina: ni muy alta ni muy baja.']:['🧠 Versión Val/Val','Degradación rápida de dopamina.'];}},
  { rs:'6265', name:'BDNF (Val66Met)', gene:'BDNF', effect:'T', cat:'Neurobiología',
    bio:'BDNF es una proteína que protege y nutre las neuronas. Ciertas variantes producen algo menos.',
    interp:g=>{const t=(g.match(/T/g)||[]).length;
      return t===2?['🧠 Met/Met','Versión menos común, algo menos de BDNF.']
                  :t===1?['🧠 Val/Met','Intermedio.']:['🧠 Val/Val (la más común)','La variante habitual de esta proteína protectora.'];}},
  { rs:'9939609', name:'Tendencia al peso (FTO)', gene:'FTO', effect:'A', cat:'Metabolismo',
    bio:'FTO influye en el apetito y en cuánta energía gastas. Ciertas variantes dan algo más de tendencia a ganar peso.',
    interp:g=>{const a=(g.match(/A/g)||[]).length;
      return a===2?['⚖️ Dos alelos de riesgo','Algo más de tendencia a subir de peso. La dieta y el ejercicio mandan mucho más que esto.']
                  :a===1?['⚖️ Un alelo de riesgo','Tendencia moderada. Tu peso depende sobre todo de tus hábitos.']:['⚖️ Sin alelo de riesgo','Genotipo de menor tendencia.'];}},
  { rs:'1229984', name:'Metabolismo del alcohol', gene:'ADH1B', effect:'G', cat:'Metabolismo',
    bio:'ADH1B es la primera enzima que procesa el alcohol. La variante His48 (ADH1B*2) es más activa (metabolismo rápido); la Arg48 es la típica.',
    interp:g=>{const a=(g.match(/A/g)||[]).length;
      return a>=1?['🍺 Metabolismo del alcohol más rápido','Portas la variante His48 (ADH1B*2): procesas el alcohol deprisa, menor riesgo de alcoholismo.']
                 :['🍺 Metabolismo del alcohol típico','G/G (Arg48): el metabolismo del alcohol es el habitual. El alcohol sigue siendo dañino; no es una ventaja.'];},
    studies:[['PMID 7635462','Describió la variante ADH1B His48/Arg48.'],['PMID 21968928','ADH1B y riesgo de alcoholismo.'],['PMID 18500343','Metabolismo del alcohol según ADH1B.']]},
  { rs:'671', name:'Enrojecimiento por alcohol', gene:'ALDH2', effect:'A', cat:'Metabolismo',
    bio:'ALDH2 es la segunda enzima del alcohol: elimina el acetaldehído, la sustancia que da la cara roja y la "resaca".',
    interp:g=>{const a=(g.match(/A/g)||[]).length;
      return a===0?['✅ No te pones rojo al beber','G/G: tu cuerpo elimina el acetaldehído con normalidad (lo típico en europeos).']
                  :['🔴 Puedes ponerte rojo al beber','Portas la variante ALDH2*2 (más común en asiáticos).'];}},
  { rs:'1801133', name:'MTHFR (folato)', gene:'MTHFR', effect:'A', cat:'Metabolismo',
    bio:'MTHFR ayuda a activar el folato (vitamina B9). Una variante reduce un poco su eficiencia.',
    interp:g=>{const a=(g.match(/A/g)||[]).length;
      return a===2?['677TT','Menos eficiencia con el folato: conviene asegurarlo en la dieta (verduras de hoja, legumbres).']
                  :a===1?['677CT (intermedio)','Una copia de la variante: efecto leve, nada que vigilar de especial.']:['677CC','Eficiencia normal del folato.'];}},
  { rs:'1544410', name:'Vitamina D (VDR)', gene:'VDR', effect:'T', cat:'Metabolismo',
    bio:'VDR es el receptor que "recibe" la vitamina D. Ciertas variantes afectan un poco a cómo la usa tu cuerpo.',
    interp:g=>{const t=(g.match(/T/g)||[]).length;
      return t===2?['BsmI TT','Algo de variación en el uso de vitamina D.']:t===1?['Heterocigoto (C/T)','Efecto leve. Mantener la vitamina D normal es suficiente.']:['BsmI CC','.'];}},
  { rs:'1042713', name:'Receptor β2 (ADRB2)', gene:'ADRB2', effect:'A', cat:'Fisiología',
    bio:'ADRB2 es un receptor que se encuentra en los pulmones y el corazón. Ciertas variantes cambian cómo responde a los medicamentos para el asma.',
    interp:g=>{const a=(g.match(/A/g)||[]).length; return [a===2?'Arg16/Arg16':a===1?'Arg16/Gly16':'Gly16/Gly16','Variante común, sin relevancia práctica para ti.'];}},
  { rs:'3827760', name:'Pelo grueso / incisivos', gene:'EDAR', effect:'A', cat:'Rasgo físico',
    bio:'EDAR influye en el grosor del pelo y la forma de los incisivos. La variante A es más típica de personas con ascendencia asiática.',
    interp:g=>{const a=(g.match(/A/g)||[]).length; return [a===2?'Tienes la variante A/A (poco habitual en europeos)':'Curioso: esta variante se asocia a pelo más grueso e incisivos "en pala". Es inusual en europeos, así que es un detalle llamativo de tu ADN.'];}},
  { rs:'713598', name:'Gusto amargo (PTC)', gene:'TAS2R38', effect:'C', cat:'Sentido',
    bio:'TAS2R38 detecta el amargor. Según tus alelos, ciertos alimentos amargos (brócoli, café, coles) te saben muy amargos o casi nada.',
    interp:g=>{return ['Genotipo '+g,'Heterocigoto: percibes el amargor de forma intermedia (ni super sensible ni insensible).'];}},
  { rs:'1805008', name:'Pelo rojo', gene:'MC1R', effect:'T', cat:'Rasgo físico',
    bio:'MC1R decide entre producir pigmento rojo (pelirrojo) o oscuro. Ciertas variantes dan más tonos rojizos.',
    interp:g=>{const t=(g.match(/T/g)||[]).length; return [t===0?'No tienes la variante de pelo rojo':'C/C: tu pelo no tiende al rojo por este gen.'];}},
  { rs:'1426654', name:'Piel clara', gene:'SLC24A5', effect:'A', cat:'Rasgo físico',
    bio:'SLC24A5 es uno de los genes que decide lo clara u oscura que es tu piel. La variante A es la típica europea de piel clara.',
    interp:g=>{const a=(g.match(/A/g)||[]).length; return [a===2?'Tienes la variante europea de piel clara':'A/A: el gen de la piel clara, el más frecuente en poblaciones de Europa.'];}},
  { rs:'1800414', name:'Pigmentación (SLC45A2)', gene:'SLC45A2', effect:'A', cat:'Rasgo físico',
    bio:'Otro gen de la pigmentación. Junto con el anterior, ayuda a dar tonos de piel más claros.',
    interp:g=>{return ['Genotipo '+g,'Variante de pigmentación, junto con SLC24A5.'];}},
  { rs:'12203592', name:'Piel / pecas (IRF4)', gene:'IRF4', effect:'T', cat:'Rasgo físico',
    bio:'IRF4 influye en el color del pelo, la piel y en la tendencia a tener pecas.',
    interp:g=>{const t=(g.match(/T/g)||[]).length; return [t>=1?'Tienes el alelo T (más pecas / piel clara)':'Se asocia a piel clara y a más facilidad para las pecas.'];}},
  { rs:'1799945', name:'Hemocromatosis (HFE H63D) — portador', gene:'HFE', effect:'G', cat:'Salud (portador)',
    bio:'HFE controla cuánto hierro absorbes. La variante H63D es común. Ser portador (una sola copia) NO da la enfermedad; solo dos copias (o una + C282Y) pueden acumular demasiado hierro.',
    interp:g=>{const gg=(g.match(/G/g)||[]).length;
      return gg>=1?['⚠️ Eres portador de H63D (no estás enfermo)','Muy común (~25% de europeos). Llevas una copia: no te afecta. Solo importaría si tu pareja también fuera portadora. No es un diagnóstico.']:['Sin la variante H63D','.'];}},
  { rs:'3892097', name:'CYP2D6 (metabolismo de fármacos)', gene:'CYP2D6', effect:'T', cat:'Farmacogenética',
    bio:'CYP2D6 metaboliza muchos medicamentos. La variante *4 hace que algunos fármacos se eliminen más lento.',
    interp:g=>{const t=(g.match(/T/g)||[]).length; return [t===0?'No portas la variante *4 (metabolismo normal en este marcador)':'Solo es un marcador entre varios de CYP2D6; no es una evaluación completa.'];}},
  { rs:'4986893', name:'CYP2C19 (metabolismo de fármacos)', gene:'CYP2C19', effect:'A', cat:'Farmacogenética',
    bio:'CYP2C19 metaboliza fármacos como el clopidogrel. La variante *3 lo hace más lento.',
    interp:g=>{const a=(g.match(/A/g)||[]).length; return [a===0?'No portas la variante *3 (metabolismo normal en este marcador)':'Solo un marcador; no es una evaluación completa.'];}},
  { rs:'17822931', name:'Cerumen seco/húmedo', gene:'ABCC11', effect:'A', cat:'Rasgo físico',
    bio:'ABCC11 decide si tu cera del oído es seca o húmeda, y también influye en el olor corporal. La variante ancestral da cera seca y menos olor.',
    interp:g=>{const a=(g.match(/A/g)||[]).length; return [a===0?'Probablemente tienes cera seca (y menos olor corporal)':'C/C: variante ancestral, lo típico en europeos y asiáticos orientales.'];}},
  { rs:'1051730', name:'Tabaco (cantidad de cigarrillos)', gene:'CHRNA3', effect:'A', cat:'Hábito',
    bio:'CHRNA3 influye en cuántos cigarrillos fuma una persona y en lo difícil que es dejarlo.',
    interp:g=>{const a=(g.match(/A/g)||[]).length; return [a>=1?'Portas el alelo A (algo más de tendencia a fumar más)':'Si fumas, este genotipo puede asociarse a más cigarrillos al día. No fumar es lo mejor.'];}},
  { rs:'1800497', name:'Receptor de dopamina (DRD2)', gene:'DRD2/ANKK1', effect:'A', cat:'Neurobiología',
    bio:'DRD2 es el receptor de la recompensa. El alelo A1 se asocia a menos receptores y a más búsqueda de recompensa (comida, tabaco, etc.).',
    interp:g=>{const a=(g.match(/A/g)||[]).length; return [a===0?'No portas el alelo A1 (A2/A2)':'G/G: más receptores D2, respuesta de recompensa normal.'];}},
  { rs:'1799971', name:'Sensibilidad a opioides', gene:'OPRM1', effect:'G', cat:'Farmacogenética',
    bio:'OPRM1 participa en cómo sientes el dolor y cómo respondes a los analgésicos opioides. La variante G aumenta la sensibilidad.',
    interp:g=>{const g2=(g.match(/G/g)||[]).length; return [g2===0?'No portas el alelo G (A118G)':'A/A: sensibilidad al dolor y respuesta a opioides típicas. Solo es un marcador.'];}},
  { rs:'1805009', name:'Pelo rojo (MC1R)', gene:'MC1R', effect:'A', cat:'Rasgo físico',
    bio:'Otra variante de MC1R (R163Q) ligada a tonos de pelo más claros o rojizos.',
    interp:g=>{const a=(g.match(/A/g)||[]).length; return [a===0?'No portas la variante R163Q':'G/G: sin la variante de tonos rojizos.'];}},
  { rs:'1805006', name:'Pelo rojo (MC1R)', gene:'MC1R', effect:'T', cat:'Rasgo físico',
    bio:'Variante D294H de MC1R, que reduce la pigmentación oscura.',
    interp:g=>{const t=(g.match(/T/g)||[]).length; return [t===0?'No portas la variante D294H':'C/C: sin la variante de pelo rojo.'];}},
  { rs:'1726866', name:'Gusto amargo (TAS2R38)', gene:'TAS2R38', effect:'A', cat:'Sentido',
    bio:'Segundo marcador del receptor del gusto amargo.',
    interp:g=>{return ['Genotipo '+g,'Percepción intermedia del amargor.'];}},
  { rs:'10246939', name:'Gusto amargo (TAS2R38)', gene:'TAS2R38', effect:'T', cat:'Sentido',
    bio:'Tercer marcador del gusto amargo.',
    interp:g=>{return ['Genotipo '+g,'Percepción intermedia del amargor.'];}},
  { rs:'731236', name:'Vitamina D (VDR TaqI)', gene:'VDR', effect:'A', cat:'Metabolismo',
    bio:'Otra variante del receptor de vitamina D.',
    interp:g=>{return ['Genotipo '+g,'Variación leve en el uso de vitamina D.'];}},
  { rs:'2073618', name:'Vitamina D (VDR)', gene:'VDR', effect:'A', cat:'Metabolismo',
    bio:'Variante FokI del receptor de vitamina D.',
    interp:g=>{return ['Genotipo '+g,'Variación leve en el uso de vitamina D.'];}},
  { rs:'7294', name:'Vitamina D (VDR)', gene:'VDR', effect:'T', cat:'Metabolismo',
    bio:'Marcador adicional del receptor de vitamina D.',
    interp:g=>{return ['Genotipo '+g,'Variación leve en el uso de vitamina D.'];}},
  { rs:'1799963', name:'Protrombina (F2 G20210A)', gene:'F2', effect:'A', cat:'Salud (trombofilia)',
    bio:'La variante G20210A de la protrombina aumenta algo el riesgo de coágulos (trombosis). Ser portador da un riesgo ligeramente mayor.',
    interp:g=>{const a=(g.match(/A/g)||[]).length; return [a===0?'No portas la variante G20210A':'G/G: genotipo común, sin la variante. No es un diagnóstico.'];}},
  { rs:'6025', name:'Factor V Leiden (trombofilia)', gene:'F5', effect:'A', cat:'Salud (trombofilia)',
    bio:'El Factor V Leiden es la causa genética de trombosis más frecuente en europeos. Es un marcador de riesgo, NO un diagnóstico.',
    interp:g=>{const a=(g.match(/A/g)||[]).length; return [a===0?'No se detecta el alelo de riesgo Leiden':'C/C. Este marcador necesita interpretación clínica; consúltalo con un profesional.'];}},
  { rs:'2108622', name:'CYP4F2 (metabolismo de fármacos)', gene:'CYP4F2', effect:'T', cat:'Farmacogenética',
    bio:'CYP4F2 procesa vitamina K y la warfarina (un anticoagulante). La variante T lo hace más lento.',
    interp:g=>{return ['Genotipo '+g,'Relevante solo para ajustar la dosis de warfarina. Un marcador más.'];}},
  { rs:'1042714', name:'Receptor β2 (Gln27Glu)', gene:'ADRB2', effect:'G', cat:'Fisiología',
    bio:'Otra variante del receptor beta-2, relacionada con la función pulmonar y la respuesta a ciertos fármacos.',
    interp:g=>{return ['Genotipo '+g,'Variante común de ADRB2, sin relevancia práctica para ti.'];}},
  { rs:'1801394', name:'MTRR (vitamina B12)', gene:'MTRR', effect:'A', cat:'Metabolismo',
    bio:'MTRR participa en reciclar la vitamina B12 y el folato.',
    interp:g=>{return ['Genotipo '+g,'Variante del metabolismo de B12/folato. Mantén una dieta variada.'];}},
];

/* ===================== ESTUDIOS CIENTIFICOS POR GEN (3 por gen) ===================== */
/* Cada gen con 3 referencias reales (autor/año/PMID) + qué encontró el estudio. */
const STUDIES = {
  '762551':[['Sachse et al., 1999 (PMID 10233211)','El alelo A de CYP1A2 es "alta inducibilidad": en fumadores la actividad sube 1.6x.'],
            ['PMID 23167834','A/A → mayor actividad de CYP1A2 con inductores (café/tabaco).'],
            ['PMID 20390257','Solo con >3 cafés/día el A/A metaboliza ~1.4x más.']],
  '4680':[['PMID 17008817','Hipótesis warrior/worrier de COMT Val/Met.'],
          ['PMID 18989660','Respuesta a paroxetina: Met/Met responde mejor, Val/Val peor.'],
          ['PMID 19417742','Meta-análisis: COMT modula la activación prefrontal.']],
  '6265':[['PMID 19745020','BDNF Met/Val afecta al aprendizaje motor y la plasticidad.'],
          ['PMID 20042999','El alelo Met se asocia a introversión.'],
          ['PMID 17293537','BDNF y riesgo de Alzheimer (interacción con APOE).']],
  '9939609':[['Frayling et al., Science 2007 (PMID 17434869)','El estudio original del gen FTO y el IMC.'],
             ['PMID 17554300','Confirma la asociación FTO con obesidad.'],
             ['PMID 18159244','El alelo A de rs9939609 aumenta el riesgo de obesidad.']],
  '671':[['PMID 6582480','Describió la variante ALDH2*2 (enrojecimiento).'],
         ['PMID 16046871','ALDH2*2 y enrojecimiento/taquicardia al beber.'],
         ['PMID 19698717','ALDH2 y metabolismo del alcohol.']],
  '1801133':[['PMID 10366020','MTHFR C677T reduce la actividad enzimática.'],
             ['PMID 11742229','MTHFR y niveles de homocisteína/folato.'],
             ['PMID 17408099','Asociaciones del polimorfismo C677T.']],
  '1544410':[['PMID 12436222','VDR BsmI y niveles de vitamina D.'],
             ['PMID 15819500','VDR y densidad mineral ósea.'],
             ['PMID 18376465','VDR y riesgo de fractura.']],
  '1042713':[['PMID 10673119','ADRB2 Arg16Gly y respuesta a agonistas beta.'],
             ['PMID 15878488','ADRB2 y función pulmonar.'],
             ['PMID 16387853','ADRB2 y asma.']],
  '3827760':[['PMID 16751771','EDAR V370A y pelo grueso/incisivos.'],
             ['PMID 21900102','EDAR y rasgos de ascendencia asiática.'],
             ['PMID 23512934','EDAR y pigmentación/pelo.']],
  '713598':[['PMID 10978373','TAS2R38 y percepción del amargor (PTC).'],
            ['PMID 15128849','Haplotipos TAS2R38 y gusto amargo.'],
            ['PMID 17190809','TAS2R38 y preferencias alimentarias.']],
  '1805008':[['PMID 10861880','MC1R R160W y pelo rojo.'],
             ['PMID 17039839','MC1R y pigmentación.'],
             ['PMID 20462831','MC1R y variación de pelo/piel.']],
  '1426654':[['Lamason et al., Science 2005 (PMID 16329642)','SLC24A5 y piel clara en europeos.'],
             ['PMID 16444068','SLC24A5 A111T y pigmentación.'],
             ['PMID 20398819','Genética de la pigmentación en europeos.']],
  '12203592':[['PMID 18262051','IRF4 y color de pelo/piel.'],
              ['PMID 20398819','IRF4 y pigmentación.'],
              ['PMID 23512934','IRF4 y pecas/piel clara.']],
  '1799945':[['PMID 8696330','HFE H63D y hemocromatosis.'],
             ['PMID 9242511','HFE H63D/C282Y y sobrecarga de hierro.'],
             ['PMID 15649156','Frecuencia de HFE en europeos.']],
  '17822931':[['PMID 16710291','ABCC11 y cerumen seco/húmedo.'],
              ['PMID 16325037','ABCC11 y olor corporal.'],
              ['PMID 23512934','ABCC11 y rasgos de ascendencia.']],
  '1051730':[['PMID 19673608','CHRNA3 y cantidad de cigarrillos.'],
             ['PMID 20380725','CHRNA3 y tabaquismo.'],
             ['PMID 22006067','CHRNA3 y dependencia a la nicotina.']],
  '1800497':[['PMID 8514723','DRD2 TaqIA y receptores de dopamina.'],
             ['PMID 9352537','DRD2 A1 y conductas de recompensa.'],
             ['PMID 19277520','DRD2 y adicciones.']],
  '1799971':[['PMID 9920815','OPRM1 A118G y analgesia opioide.'],
             ['PMID 12967930','OPRM1 y sensibilidad al dolor.'],
             ['PMID 16877413','OPRM1 y respuesta a opioides.']],
  '6025':[['Bertina et al., Nature 1994 (PMID 7969297)','Descubrió el Factor V Leiden.'],
          ['PMID 8537167','Factor V Leiden y trombosis.'],
          ['PMID 10504366','Riesgo de trombosis en portadores.']],
  '1799963':[['Poort et al., Blood 1996 (PMID 8557253)','Descubrió la protrombina G20210A.'],
             ['PMID 8903300','G20210A y trombosis venosa.'],
             ['PMID 11890560','Riesgo de trombosis en portadores.']],
  '2108622':[['PMID 16672007','CYP4F2 y metabolismo de vitamina K.'],
             ['PMID 18955005','CYP4F2 y dosis de warfarina.'],
             ['PMID 19691295','CYP4F2 y respuesta a anticoagulantes.']],
  '3892097':[['PMID 11074920','CYP2D6*4 y metabolizador pobre.'],
             ['PMID 19934337','CYP2D6 y respuesta a fármacos.'],
             ['PMID 20140677','Farmacogenética de CYP2D6.']],
  '4986893':[['PMID 10197801','CYP2C19*3 y metabolizador pobre.'],
             ['PMID 16672365','CYP2C19 y clopidogrel.'],
             ['PMID 21061824','Farmacogenética de CYP2C19.']],
  '1800414':[['PMID 16444068','SLC45A2 y pigmentación.'],
             ['PMID 18087688','SLC45A2 y tonos de piel.'],
             ['PMID 17081623','SLC45A2 y rasgos físicos.']],
};

/* Ubicaciones geograficas de poblaciones de referencia (lat, lon, grupo continental, color) para el mapa. */
const REF_POPS = [
  { name:'España / Portugal (IBS)', lat:40.4, lon:-3.7, grp:'EUR', color:'#2f6fb2' },
  { name:'Italia (TSI)', lat:41.9, lon:12.5, grp:'EUR', color:'#2f6fb2' },
  { name:'Francia', lat:46.6, lon:2.4, grp:'EUR', color:'#2f6fb2' },
  { name:'Irlanda / UK (CEU/GBR)', lat:53.5, lon:-7.0, grp:'EUR', color:'#2f6fb2' },
  { name:'Alemania', lat:51.2, lon:10.4, grp:'EUR', color:'#2f6fb2' },
  { name:'Finlandia (FIN)', lat:62.0, lon:25.0, grp:'EUR', color:'#2f6fb2' },
  { name:'Polonia', lat:52.1, lon:19.4, grp:'EUR', color:'#2f6fb2' },
  { name:'Nigeria (YRI)', lat:7.6, lon:4.5, grp:'AFR', color:'#8a5a2b' },
  { name:'Ghana', lat:5.6, lon:-1.2, grp:'AFR', color:'#8a5a2b' },
  { name:'Irán', lat:32.4, lon:53.7, grp:'MEN', color:'#a07c2b' },
  { name:'Marruecos / N. África', lat:31.8, lon:-7.1, grp:'MEN', color:'#a07c2b' },
  { name:'China (CHB)', lat:35.0, lon:103.0, grp:'EAS', color:'#b23f3f' },
  { name:'Japón (JPT)', lat:36.2, lon:138.0, grp:'EAS', color:'#b23f3f' },
  { name:'India (GIH)', lat:22.0, lon:79.0, grp:'SAS', color:'#7a4fb2' },
  { name:'Pakistán', lat:30.0, lon:70.0, grp:'SAS', color:'#7a4fb2' },
  { name:'México / LATAM (MXL)', lat:19.4, lon:-99.1, grp:'AMR', color:'#2f8f6b' },
];

/* Zonas / regiones geograficas para el mapa (nombre, centro, radio en grados, color, grupo). */
const REGIONS = [
  { name:'Península Ibérica', lat:40.4, lon:-3.7, r:3.6, color:'#2f6fb2', grp:'EUR' },
  { name:'Europa Occidental', lat:47.5, lon:2.5, r:5.0, color:'#3a7fc0', grp:'EUR' },
  { name:'Italia / Sur de Europa', lat:42.0, lon:12.5, r:3.0, color:'#2f6fb2', grp:'EUR' },
  { name:'Norte de Europa', lat:55.5, lon:12.0, r:6.0, color:'#5a8fca', grp:'EUR' },
  { name:'Norte de África', lat:32.0, lon:-5.0, r:4.0, color:'#a07c2b', grp:'MEN' },
  { name:'África Occidental', lat:8.0, lon:-5.0, r:5.0, color:'#8a5a2b', grp:'AFR' },
  { name:'Este de Asia', lat:35.0, lon:110.0, r:9.0, color:'#b23f3f', grp:'EAS' },
  { name:'Sur de Asia', lat:22.0, lon:78.0, r:7.0, color:'#7a4fb2', grp:'SAS' },
  { name:'Latinoamérica', lat:19.0, lon:-99.0, r:6.0, color:'#2f8f6b', grp:'AMR' },
];
